/* UNKNOWN-UNKNOWN — demo corpus: longevity science.
   Papers are illustrative (inspired by the literature, fictional author lists).
   All gaps are COMPUTED from these links by gaps.js — nothing is hardcoded. */

const SUBFIELDS = {
  mtor:  "mTOR & Nutrient Sensing",
  sen:   "Cellular Senescence",
  nad:   "NAD+ & Sirtuins",
  met:   "Metabolic Drugs",
  diet:  "Dietary Restriction",
  mito:  "Mitochondria & Mitophagy",
  epi:   "Epigenetic Aging",
  repro: "Reprogramming & Stem Cells",
};

const ASSUMPTIONS = [
  { id: "A01", text: "Lifespan extension in short-lived, inbred mouse strains predicts benefit in humans.",
    blueprint: { approach: "Cross-species concordance study", model: "human biomarker panels + mouse lifespan",
      design: "Take 6 interventions with published mouse lifespan effect sizes. Test each in short-term human panels (n=60/arm): inflammation composite, GrimAge2, VO2max, muscle biopsy mitochondrial respiration. Pre-register rank-correlation analysis.",
      endpoints: ["Spearman rho: mouse lifespan Δ vs human biomarker Δ", "Per-intervention concordance rank"], duration: "3 years", cost: "$4–8M" } },
  { id: "A02", text: "No essential senescent-cell populations are lost when senescent cells are cleared systemically.",
    blueprint: { approach: "Lineage-traced clearance census", model: "mouse (p16-CreERT2; reporter)",
      design: "Systemic senolytic vs genetic clearance in aged mice with single-cell census of cleared populations across 12 tissues. Flag cleared clusters enriched for tissue-resident macrophages, progenitors, or wound-healing fibroblasts.",
      endpoints: ["Fraction of cleared cells that are non-senescent by transcriptome", "Tissue-repair capacity post-clearance"], duration: "2 years", cost: "$1.5–3M" } },
  { id: "A03", text: "Age-related NAD+ decline is a cause of aging, not a consequence of it.",
    blueprint: { approach: "Mendelian randomization + clamp trial", model: "human genetics + RCT",
      design: "Two-sample MR: genetic instruments for NAD+ synthesis capacity vs 8 aging outcomes in UK Biobank. Follow with a 12-month NR 'clamp' RCT (n=200) measuring whether raising NAD+ moves hard functional endpoints, not just NAD+ levels.",
      endpoints: ["MR causal estimate per outcome", "Δ 6-min walk, Δ muscle respiration at matched NAD+ rise"], duration: "4 years", cost: "$6–10M" } },
  { id: "A04", text: "Deceleration of an epigenetic clock equals genuine biological rejuvenation.",
    blueprint: { approach: "Clock-vs-lifespan calibration", model: "meta-analysis + mouse",
      design: "Assemble all published interventions with both clock Δ and lifespan Δ (target n≥40). Fit clock-Δ→lifespan-Δ transfer function. Then run a prospective mouse trial of 3 clock-decelerating interventions measuring actual lifespan.",
      endpoints: ["R² of clock Δ predicting lifespan Δ", "Prospective prediction error"], duration: "3 years", cost: "$2–4M" } },
  { id: "A05", text: "Chronic mTOR inhibition's longevity benefits outweigh its metabolic and immune costs.",
    blueprint: { approach: "Net-benefit RCT in older adults", model: "human",
      design: "2-year RCT of intermittent everolimus (n=400, 65+): composite primary of infection rate, HbA1c trajectory, and vaccine response vs epigenetic-age and inflammation benefit. Pre-specified harm–benefit tradeoff rule.",
      endpoints: ["Net clinical benefit score (benefits minus harms)", "Infection hospitalization rate"], duration: "3 years", cost: "$8–15M" } },
  { id: "A06", text: "Caloric-restriction mechanisms found in rodents apply to humans despite metabolic differences.",
    blueprint: { approach: "Mechanism-conservation mapping", model: "human (CALERIE-type) + rodent",
      design: "Deep-phenotype 100 humans on 18-month 15% CR (transcriptome, metabolome, proteome across 3 tissues) and align pathway-level changes against 6 rodent CR datasets. Quantify conserved vs divergent modules.",
      endpoints: ["Fraction of rodent CR pathway modules conserved in humans", "Divergent-module catalog"], duration: "3 years", cost: "$5–9M" } },
  { id: "A07", text: "In-vitro senescence markers (p16INK4a, SA-β-gal) faithfully identify senescent cells in vivo.",
    blueprint: { approach: "In-vivo ground-truth census", model: "mouse + human tissue",
      design: "Paired measurement in aged tissues: p16/SA-β-gal staining vs single-cell transcriptomic senescence signature vs functional SASP secretion. Compute positive predictive value of each classical marker per tissue.",
      endpoints: ["PPV of p16+ for transcriptomic senescence, by tissue", "Marker × tissue reliability matrix"], duration: "2 years", cost: "$1–2M" } },
  { id: "A08", text: "Transient partial reprogramming can be made safe — no teratoma or pluripotency risk.",
    blueprint: { approach: "Dose–duration safety surface", model: "mouse",
      design: "Systematic OSK pulse matrix (4 durations × 4 doses × 3 delivery routes) in aged wild-type mice, 18-month follow-up: teratoma screen, pluripotency gene panel, tumor incidence vs rejuvenation readouts.",
      endpoints: ["Maximum rejuvenation dose with zero teratomas at 18 mo", "Safety–efficacy frontier curve"], duration: "2.5 years", cost: "$2–4M" } },
  { id: "A09", text: "Healthspan gains in mice imply lifespan gains (and vice versa).",
    blueprint: { approach: "Healthspan–lifespan coupling meta-analysis", model: "meta + prospective mouse",
      design: "Extract paired healthspan/lifespan outcomes from 60 published intervention studies; estimate coupling coefficient and its moderators (sex, strain, intervention class). Prospectively test 4 'healthspan-only' interventions for lifespan.",
      endpoints: ["Coupling coefficient r with 95% CI", "Prospective hit rate of healthspan→lifespan"], duration: "3 years", cost: "$2–5M" } },
  { id: "A10", text: "Aging is driven by a targetable program rather than stochastic damage accumulation.",
    blueprint: { approach: "Program-vs-damage discriminator", model: "comparative + interventional",
      design: "Test programmatic predictions: (1) aging trajectories should be predictable from early-life state; (2) program blockade should compress morbidity. Compare predictive accuracy of programmatic vs damage-accumulation models on longitudinal cohorts.",
      endpoints: ["Out-of-sample trajectory prediction, program vs damage models", "Morbidity-compression test"], duration: "4 years", cost: "$3–6M" } },
  { id: "A11", text: "Mouse epigenetic clocks measure the same biology as human epigenetic clocks.",
    blueprint: { approach: "Cross-species clock alignment", model: "mouse + human",
      design: "Apply human-trained and mouse-trained clocks to both species' methylation data; test whether orthologous-CpG clocks rank interventions concordantly across 10 shared interventions.",
      endpoints: ["Cross-species intervention ranking concordance", "Orthologous-CpG clock transfer R²"], duration: "2 years", cost: "$800K–1.5M" } },
  { id: "A12", text: "Metformin's observational longevity signal is not explained by indication bias or confounding.",
    blueprint: { approach: "Target-trial emulation + genetics", model: "human EHR + MR",
      design: "Emulate a target trial in 2M-record EHR with cloning/censoring/weighting; negative-control outcomes; then drug-target MR for metformin targets (AMPK pathway instruments) vs mortality.",
      endpoints: ["Emulated trial HR with full confounding control", "Drug-target MR estimate"], duration: "2 years", cost: "$600K–1.2M" } },
  { id: "A13", text: "Mitochondrial dysfunction is upstream of the other hallmarks of aging.",
    blueprint: { approach: "Causal ordering via perturbation", model: "mouse + cell",
      design: "Inducible, tissue-specific mitochondrial rescue in aged mice; time-series multi-omics to test whether senescence, epigenetic, and proteostasis hallmarks normalize downstream — with temporal precedence analysis.",
      endpoints: ["Granger-causal ordering of hallmark reversal", "Hallmarks normalized per unit mito rescue"], duration: "3 years", cost: "$2–4M" } },
  { id: "A14", text: "Senolytic benefits persist after drug clearance — intermittent 'hit-and-run' dosing is sufficient.",
    blueprint: { approach: "Durability-of-benefit trial", model: "mouse + human",
      design: "Single senolytic course in aged mice; track function and senescent-cell re-accumulation monthly for 12 months to estimate benefit half-life. Parallel human pilot with 12-month functional follow-up after one course.",
      endpoints: ["Benefit half-life (months)", "Re-accumulation rate of senescent cells"], duration: "2 years", cost: "$1.5–3M" } },
  { id: "A15", text: "Periodic fasting produces the same core mechanisms as chronic caloric restriction.",
    blueprint: { approach: "Head-to-head mechanism trial", model: "mouse + human",
      design: "Four-arm trial: ad-lib, chronic 20% CR, periodic FMD, time-restricted feeding — matched for weight loss. Compare pathway activation (mTOR, AMPK, IGF-1, autophagy flux) and functional outcomes.",
      endpoints: ["Pathway-activation cosine similarity FMD vs CR", "Functional outcomes at matched weight loss"], duration: "2.5 years", cost: "$3–5M" } },
];

const CLAIMS = [
  { id: "C01", text: "Rapamycin extends median lifespan ~9–14% in genetically heterogeneous mice.", subfield: "mtor", models: ["mouse"] },
  { id: "C02", text: "Chronic rapamycin impairs glucose tolerance via mTORC2 disruption.", subfield: "mtor", models: ["mouse"] },
  { id: "C03", text: "Intermittent rapamycin retains lifespan benefits with fewer metabolic costs.", subfield: "mtor", models: ["mouse"] },
  { id: "C04", text: "Senolytics (D+Q) clear senescent cells and extend healthspan in aged mice.", subfield: "sen", models: ["mouse"] },
  { id: "C05", text: "Genetic clearance of p16+ cells delays age-related disorders.", subfield: "sen", models: ["mouse"] },
  { id: "C06", text: "Fisetin extends lifespan in aged mice.", subfield: "sen", models: ["mouse"] },
  { id: "C07", text: "NR/NMN robustly raise NAD+ levels in human blood and tissue.", subfield: "nad", models: ["human"] },
  { id: "C08", text: "NAD+ repletion improves mitochondrial and stem-cell function in aged mice.", subfield: "nad", models: ["mouse"] },
  { id: "C09", text: "NMN supplementation extends lifespan in mice.", subfield: "nad", models: ["mouse"] },
  { id: "C10", text: "Metformin use associates with reduced all-cause mortality vs matched controls.", subfield: "met", models: ["human"] },
  { id: "C11", text: "Metformin blunts exercise-induced mitochondrial adaptations in older adults.", subfield: "met", models: ["human"] },
  { id: "C12", text: "Caloric restriction extends lifespan in rhesus monkeys (WNPRC study).", subfield: "diet", models: ["monkey"] },
  { id: "C13", text: "Diet composition and feeding regimen explain the WNPRC–NIA divergence.", subfield: "diet", models: ["monkey"] },
  { id: "C14", text: "Fasting-mimicking diet improves metabolic risk markers in humans.", subfield: "diet", models: ["human"] },
  { id: "C15", text: "Methionine restriction extends lifespan independent of total calories.", subfield: "diet", models: ["mouse"] },
  { id: "C16", text: "Urolithin A restores mitophagy and improves muscle function.", subfield: "mito", models: ["mouse", "human"] },
  { id: "C17", text: "Spermidine extends lifespan across species via autophagy induction.", subfield: "mito", models: ["worm", "mouse"] },
  { id: "C18", text: "Epigenetic age (GrimAge) predicts all-cause mortality in humans.", subfield: "epi", models: ["human"] },
  { id: "C19", text: "Clock deceleration by interventions does not reliably predict lifespan extension.", subfield: "epi", models: ["multi"] },
  { id: "C20", text: "Partial in-vivo reprogramming extends lifespan in progeroid mice.", subfield: "repro", models: ["mouse"] },
  { id: "C21", text: "Continuous OSK expression causes teratomas and premature death in mice.", subfield: "repro", models: ["mouse"] },
  { id: "C22", text: "Short-pulse OSK improves regeneration without teratomas.", subfield: "repro", models: ["mouse"] },
  { id: "C23", text: "Young systemic milieu rejuvenates aged progenitor cells (parabiosis).", subfield: "repro", models: ["mouse"] },
  { id: "C24", text: "Senescent cells accumulate with age in human tissues.", subfield: "sen", models: ["human", "mouse"] },
  { id: "C25", text: "p16 marks activated macrophages, not only senescent cells.", subfield: "sen", models: ["mouse"] },
  { id: "C26", text: "Senomorphics suppress SASP and frailty without killing senescent cells.", subfield: "sen", models: ["mouse"] },
  { id: "C27", text: "mTOR inhibition improves elderly immune response to vaccination.", subfield: "mtor", models: ["human"] },
  { id: "C28", text: "Mitochondrial dysfunction precedes senescence and stem-cell exhaustion.", subfield: "mito", models: ["mouse"] },
  { id: "C29", text: "Mouse and human epigenetic clocks share underlying CpG biology.", subfield: "epi", models: ["multi"] },
  { id: "C30", text: "Transient reprogramming resets epigenetic age in vitro without pluripotency.", subfield: "epi", models: ["cell"] },
];

/* asserts: claim ids the paper supports · contradicts: claim ids it argues against
   reliesOn: assumption ids the conclusions depend on · tests: assumption ids directly probed */
const PAPERS = [
  // ---- mTOR & Nutrient Sensing ----
  { id: "P01", title: "Rapamycin fed late in life extends lifespan in genetically heterogeneous mice",
    authors: ["Harrison, D.E.", "Strong, R.", "Sharp, Z.D."], year: 2009, venue: "Nature", subfield: "mtor", model: "mouse",
    asserts: ["C01"], contradicts: [], reliesOn: ["A01", "A05", "A09"], tests: [],
    methods: ["lifespan assay", "heterogeneous stock"], cites: [] },
  { id: "P02", title: "Rapamycin extends lifespan and delays cancer even when initiated at 20 months of age",
    authors: ["Miller, R.A.", "Harrison, D.E.", "Astle, C.M."], year: 2011, venue: "Aging Cell", subfield: "mtor", model: "mouse",
    asserts: ["C01"], contradicts: [], reliesOn: ["A01"], tests: [],
    methods: ["lifespan assay", "late-life intervention"], cites: ["P01"] },
  { id: "P03", title: "Chronic rapamycin treatment impairs glucose tolerance via mTORC2 disruption",
    authors: ["Lamming, D.W.", "Ye, L.", "Sabatin, D.M."], year: 2012, venue: "Science", subfield: "mtor", model: "mouse",
    asserts: ["C02"], contradicts: [], reliesOn: [], tests: ["A05"],
    methods: ["glucose clamp", "tissue-specific KO"], cites: ["P01"] },
  { id: "P04", title: "Intermittent rapamycin dosing retains longevity benefits with reduced metabolic disruption",
    authors: ["Arriola Apelo, S.I.", "Lamming, D.W."], year: 2016, venue: "Aging Cell", subfield: "mtor", model: "mouse",
    asserts: ["C03"], contradicts: [], reliesOn: ["A05", "A01"], tests: ["A05"],
    methods: ["lifespan assay", "intermittent dosing"], cites: ["P01", "P03"] },
  { id: "P05", title: "mTOR inhibition improves immune response to influenza vaccination in elderly volunteers",
    authors: ["Mannick, J.B.", "Del Giudice, G.", "Lattanzi, M."], year: 2014, venue: "Science Transl. Med.", subfield: "mtor", model: "human",
    asserts: ["C27"], contradicts: [], reliesOn: ["A01"], tests: [],
    methods: ["randomized trial", "vaccine challenge"], cites: ["P01"] },

  // ---- Cellular Senescence ----
  { id: "P06", title: "Senescent cells accumulate with age and localize to sites of age-related pathology",
    authors: ["Herbig, U.", "Ferreira, M.", "Condel, L."], year: 2006, venue: "Mech. Ageing Dev.", subfield: "sen", model: "human",
    asserts: ["C24"], contradicts: [], reliesOn: ["A07"], tests: [],
    methods: ["immunohistochemistry", "SA-β-gal"], cites: [] },
  { id: "P07", title: "Clearance of p16Ink4a-positive cells delays ageing-associated disorders",
    authors: ["Baker, D.J.", "Wijshake, T.", "Tchkonia, T."], year: 2011, venue: "Nature", subfield: "sen", model: "mouse",
    asserts: ["C05"], contradicts: [], reliesOn: ["A02", "A07"], tests: [],
    methods: ["transgenic clearance", "healthspan battery"], cites: ["P06"] },
  { id: "P08", title: "Dasatinib plus quercetin clears senescent cells and alleviates physical dysfunction in aged mice",
    authors: ["Xu, M.", "Pirtskhalava, T.", "Farr, J.N."], year: 2018, venue: "Nature Medicine", subfield: "sen", model: "mouse",
    asserts: ["C04"], contradicts: [], reliesOn: ["A02", "A07", "A14"], tests: [],
    methods: ["senolytic dosing", "frailty index"], cites: ["P06", "P07"] },
  { id: "P09", title: "First-in-human trial: senolytics decrease senescent cell burden in diabetic kidney disease",
    authors: ["Hickson, L.J.", "Langhi Prata, L.G.", "Bobart, S.A."], year: 2019, venue: "EBioMedicine", subfield: "sen", model: "human",
    asserts: [], contradicts: [], reliesOn: ["A07", "A01"], tests: ["A07"],
    methods: ["open-label pilot", "adipose biopsy"], cites: ["P08"] },
  { id: "P10", title: "Dasatinib plus quercetin shows no functional improvement in idiopathic pulmonary fibrosis: pilot RCT",
    authors: ["Justice, J.N.", "Nambiar, A.M.", "Tchkonia, T."], year: 2021, venue: "EBioMedicine", subfield: "sen", model: "human",
    asserts: [], contradicts: ["C04"], reliesOn: [], tests: ["A14"],
    methods: ["randomized pilot", "6-min walk"], cites: ["P08", "P09"] },
  { id: "P11", title: "p16INK4a expression marks activated macrophages, not exclusively senescent cells",
    authors: ["Hall, B.M.", "Biran, V.", "Nakanishi, M."], year: 2017, venue: "Aging", subfield: "sen", model: "mouse",
    asserts: ["C25"], contradicts: [], reliesOn: [], tests: ["A07"],
    methods: ["lineage tracing", "scRNA-seq"], cites: ["P06", "P07"] },
  { id: "P12", title: "Fisetin extends healthspan and lifespan in aged mice",
    authors: ["Yousefzadeh, M.J.", "Zhu, Y.", "McGowan, S.J."], year: 2018, venue: "EBioMedicine", subfield: "sen", model: "mouse",
    asserts: ["C06"], contradicts: [], reliesOn: ["A02", "A14", "A01"], tests: [],
    methods: ["lifespan assay", "late-life dosing"], cites: ["P08"] },
  { id: "P40", title: "JAK inhibition suppresses the senescence-associated secretory phenotype and frailty without cell killing",
    authors: ["Xu, M.", "Tchkonia, T.", "Kirkland, J.L."], year: 2015, venue: "PNAS", subfield: "sen", model: "mouse",
    asserts: ["C26"], contradicts: [], reliesOn: ["A02"], tests: [],
    methods: ["SASP profiling", "frailty index"], cites: ["P08"] },

  // ---- NAD+ & Sirtuins ----
  { id: "P13", title: "NAD+ repletion improves mitochondrial and stem cell function and extends lifespan in mice",
    authors: ["Zhang, H.", "Ryu, D.", "Wu, Y."], year: 2016, venue: "Science", subfield: "nad", model: "mouse",
    asserts: ["C08"], contradicts: [], reliesOn: ["A03", "A01"], tests: [],
    methods: ["NR supplementation", "muscle stem cell assay"], cites: [] },
  { id: "P14", title: "Nicotinamide riboside dose-dependently raises NAD+ in healthy human volunteers",
    authors: ["Trammell, S.A.", "Schmidt, M.S.", "Weidemann, B.J."], year: 2016, venue: "Nature Commun.", subfield: "nad", model: "human",
    asserts: ["C07"], contradicts: [], reliesOn: [], tests: [],
    methods: ["dose escalation", "PBMC NAD+"], cites: ["P13"] },
  { id: "P15", title: "Twelve weeks of nicotinamide riboside does not improve mitochondrial function in human skeletal muscle",
    authors: ["Dollerup, O.L.", "Chubanava, S.", "Agerholm, M."], year: 2019, venue: "J. Physiol.", subfield: "nad", model: "human",
    asserts: [], contradicts: ["C08"], reliesOn: [], tests: ["A03"],
    methods: ["randomized trial", "muscle biopsy respiration"], cites: ["P13", "P14"] },
  { id: "P16", title: "Long-term NMN supplementation extends lifespan and healthspan in mice",
    authors: ["Mills, K.F.", "Yoshida, S.", "Stein, L.R."], year: 2021, venue: "Cell Metabolism", subfield: "nad", model: "mouse",
    asserts: ["C09"], contradicts: [], reliesOn: ["A03", "A01"], tests: [],
    methods: ["lifespan assay", "longitudinal frailty"], cites: ["P13"] },
  { id: "P17", title: "Chronic NMN administration fails to extend lifespan in C57BL/6J mice",
    authors: ["Peterson, A.L.", "Nguyen, T.", "Sorci, C."], year: 2023, venue: "Aging Cell", subfield: "nad", model: "mouse",
    asserts: [], contradicts: ["C09"], reliesOn: [], tests: [],
    methods: ["lifespan assay", "independent replication"], cites: ["P16"] },

  // ---- Metabolic Drugs ----
  { id: "P18", title: "Metformin use is associated with reduced all-cause mortality versus matched non-diabetic controls",
    authors: ["Bannister, C.A.", "Holden, S.E.", "Jenkins-Jones, S."], year: 2014, venue: "Diabetes Obes. Metab.", subfield: "met", model: "human",
    asserts: ["C10"], contradicts: [], reliesOn: ["A12"], tests: [],
    methods: ["retrospective cohort", "propensity matching"], cites: [] },
  { id: "P19", title: "The metformin mortality benefit attenuates to null after adjustment for BMI, smoking and frailty",
    authors: ["Stevenson, K.R.", "Omar, R.", "Lindsey, P."], year: 2020, venue: "Diabetes Care", subfield: "met", model: "human",
    asserts: [], contradicts: ["C10"], reliesOn: [], tests: ["A12"],
    methods: ["re-analysis", "full confounder adjustment"], cites: ["P18"] },
  { id: "P20", title: "Metformin blunts VO2max and mitochondrial adaptations to aerobic exercise in older adults",
    authors: ["Konopka, A.R.", "Laurin, J.L.", "Schoenberg, H.M."], year: 2019, venue: "Aging Cell", subfield: "met", model: "human",
    asserts: ["C11"], contradicts: [], reliesOn: [], tests: [],
    methods: ["randomized trial", "exercise training"], cites: ["P18"] },
  { id: "P21", title: "Design of the TAME trial: a 6-year RCT of metformin against composite aging endpoints",
    authors: ["Barzilai, N.", "Crandall, J.P.", "Huffman, D.M."], year: 2018, venue: "Cell", subfield: "met", model: "human",
    asserts: [], contradicts: [], reliesOn: ["A12"], tests: [],
    methods: ["trial design", "composite endpoints"], cites: ["P18", "P19"] },

  // ---- Dietary Restriction ----
  { id: "P22", title: "Caloric restriction delays disease onset and mortality in rhesus monkeys (WNPRC)",
    authors: ["Colman, R.J.", "Anderson, R.M.", "Johnson, S.C."], year: 2009, venue: "Science", subfield: "diet", model: "monkey",
    asserts: ["C12"], contradicts: [], reliesOn: ["A06", "A09"], tests: [],
    methods: ["20-year longitudinal", "primate colony"], cites: [] },
  { id: "P23", title: "Caloric restriction does not extend lifespan in rhesus monkeys (NIA study)",
    authors: ["Mattison, J.A.", "Roth, G.S.", "Beasley, T.M."], year: 2012, venue: "Nature", subfield: "diet", model: "monkey",
    asserts: [], contradicts: ["C12"], reliesOn: [], tests: ["A06"],
    methods: ["23-year longitudinal", "primate colony"], cites: ["P22"] },
  { id: "P24", title: "Diet composition and feeding regimen reconcile the WNPRC–NIA caloric restriction divergence",
    authors: ["Mattison, J.A.", "Colman, R.J.", "Beasley, T.M."], year: 2017, venue: "Nature Commun.", subfield: "diet", model: "monkey",
    asserts: ["C13"], contradicts: [], reliesOn: [], tests: [],
    methods: ["comparative re-analysis", "diet harmonization"], cites: ["P22", "P23"] },
  { id: "P25", title: "Fasting-mimicking diet reduces cardiometabolic risk factors: randomized human trial",
    authors: ["Wei, M.", "Brandhorst, S.", "Longo, V.D."], year: 2017, venue: "Sci. Transl. Med.", subfield: "diet", model: "human",
    asserts: ["C14"], contradicts: [], reliesOn: ["A15", "A06"], tests: [],
    methods: ["randomized trial", "periodic FMD"], cites: ["P22"] },
  { id: "P26", title: "Methionine restriction extends lifespan independent of total caloric intake",
    authors: ["Miller, R.A.", "Buehner, G.", "Chang, Y."], year: 2005, venue: "Aging Cell", subfield: "diet", model: "mouse",
    asserts: ["C15"], contradicts: [], reliesOn: [], tests: [],
    methods: ["amino-acid defined diets", "lifespan assay"], cites: [] },

  // ---- Mitochondria & Mitophagy ----
  { id: "P27", title: "Mitophagy declines with age; urolithin A restores mitophagy and muscle function",
    authors: ["Ryu, D.", "Mouchiroud, L.", "Andreux, P.A."], year: 2016, venue: "Nature Medicine", subfield: "mito", model: "mouse",
    asserts: ["C16"], contradicts: [], reliesOn: ["A13", "A01"], tests: [],
    methods: ["mitophagy reporter", "muscle endurance"], cites: [] },
  { id: "P28", title: "Urolithin A improves muscle endurance in older adults: phase 2 randomized trial",
    authors: ["Andreux, P.A.", "Blanco-Bose, W.", "Ryu, D."], year: 2022, venue: "Cell Rep. Med.", subfield: "mito", model: "human",
    asserts: ["C16"], contradicts: [], reliesOn: ["A13", "A01"], tests: [],
    methods: ["randomized trial", "muscle biopsy"], cites: ["P27"] },
  { id: "P29", title: "Spermidine induces autophagy and extends lifespan across species",
    authors: ["Eisenberg, T.", "Knauer, H.", "Madeo, F."], year: 2016, venue: "Nature Medicine", subfield: "mito", model: "worm",
    asserts: ["C17"], contradicts: [], reliesOn: [], tests: [],
    methods: ["autophagy flux", "cross-species lifespan"], cites: [] },
  { id: "P30", title: "Mitochondrial dysfunction precedes senescence and stem-cell exhaustion in aging",
    authors: ["Wiley, C.D.", "Velarde, M.C.", "Campisi, J."], year: 2016, venue: "Cell Metabolism", subfield: "mito", model: "mouse",
    asserts: ["C28"], contradicts: [], reliesOn: ["A13"], tests: [],
    methods: ["longitudinal tracking", "senescence reporters"], cites: ["P27"] },

  // ---- Epigenetic Aging ----
  { id: "P31", title: "DNA methylation GrimAge strongly predicts all-cause mortality",
    authors: ["Lu, A.T.", "Quach, A.", "Wilson, J.G."], year: 2019, venue: "Aging", subfield: "epi", model: "human",
    asserts: ["C18"], contradicts: [], reliesOn: [], tests: [],
    methods: ["EWAS", "survival analysis"], cites: [] },
  { id: "P32", title: "Epigenetic clock deceleration does not reliably predict lifespan extension: systematic review",
    authors: ["Mei, X.", "Blanchard, J.", "Field, A.E."], year: 2023, venue: "Nature Aging", subfield: "epi", model: "multi",
    asserts: ["C19"], contradicts: [], reliesOn: [], tests: ["A04"],
    methods: ["systematic review", "transfer-function fit"], cites: ["P31"] },
  { id: "P33", title: "Mouse and human epigenetic clocks share orthologous CpG biology",
    authors: ["Stubbs, T.M.", "Bonder, M.J.", "Stubbs, T."], year: 2021, venue: "Genome Biology", subfield: "epi", model: "multi",
    asserts: ["C29"], contradicts: [], reliesOn: ["A11"], tests: ["A11"],
    methods: ["cross-species EWAS", "ortholog mapping"], cites: ["P31"] },
  { id: "P34", title: "Maturation-phase transient reprogramming resets epigenetic age in human fibroblasts",
    authors: ["Gill, D.", "Parry, A.", "Santos, F."], year: 2022, venue: "eLife", subfield: "epi", model: "cell",
    asserts: ["C30"], contradicts: [], reliesOn: ["A08", "A04"], tests: [],
    methods: ["transient OSKM", "multi-clock readout"], cites: ["P31"] },

  // ---- Reprogramming & Stem Cells ----
  { id: "P35", title: "In vivo partial reprogramming extends lifespan in a mouse model of premature aging",
    authors: ["Ocampo, A.", "Reddy, P.", "Martinez-Redondo, P."], year: 2016, venue: "Cell", subfield: "repro", model: "mouse",
    asserts: ["C20"], contradicts: [], reliesOn: ["A08", "A01"], tests: [],
    methods: ["cyclic OSKM induction", "progeroid model"], cites: [] },
  { id: "P36", title: "Continuous in vivo OSKM expression causes teratomas and premature death",
    authors: ["Abad, M.", "Mosteiro, L.", "Pantoja, C."], year: 2013, venue: "Nature", subfield: "repro", model: "mouse",
    asserts: ["C21"], contradicts: [], reliesOn: [], tests: ["A08"],
    methods: ["constitutive induction", "tumor screen"], cites: [] },
  { id: "P37", title: "Short-pulse OSK delivery improves muscle regeneration in aged mice without teratomas",
    authors: ["Chae, D.", "L'Honoré, Q.", "Rando, T.A."], year: 2024, venue: "Cell Stem Cell", subfield: "repro", model: "mouse",
    asserts: ["C22"], contradicts: [], reliesOn: ["A08"], tests: ["A08"],
    methods: ["AAV pulse", "injury-regeneration assay"], cites: ["P35", "P36"] },
  { id: "P38", title: "Heterochronic parabiosis rejuvenates aged progenitor cells via the young systemic milieu",
    authors: ["Conboy, I.M.", "Conboy, M.J.", "Wagers, A.J."], year: 2005, venue: "Nature", subfield: "repro", model: "mouse",
    asserts: ["C23"], contradicts: [], reliesOn: ["A10"], tests: [],
    methods: ["parabiosis", "progenitor assays"], cites: [] },
  { id: "P39", title: "Dilution of old plasma, not young factors, explains parabiosis rejuvenation effects",
    authors: ["Mehdipour, M.", "Skinner, C.", "Wong, N."], year: 2020, venue: "Aging", subfield: "repro", model: "mouse",
    asserts: [], contradicts: ["C23"], reliesOn: [], tests: [],
    methods: ["neutral blood exchange", "proteomics"], cites: ["P38"] },
];
