"use strict";
var GC = window.GC || (window.GC = {});

/* 45 normal categories */
GC.CATS = ["Random","Food","Drinks","Fast Food","Snacks","Desserts","Travel","Vacation","Cities",
"Lifestyle","Money","Dating","Relationships","Couples","Friendship","Family","Personality","Pet Peeves",
"Would You Rather","Hypotheticals","Chaos","Internet","Memes","Nostalgia","Childhood","Music","Movies",
"TV","Video Games","Sports","Hobbies","School","Work","Fashion","Beauty","Shopping","Home","Animals",
"Experiences","Bucket List","Embarrassing","Gross","Deep","Wholesome","Unhinged"];

/* category sections for the select screen (Spicy gets its own when enabled) */
GC.SECTIONS = [
  { name: "Food & Drink", cats: ["Food","Drinks","Fast Food","Snacks","Desserts"] },
  { name: "People", cats: ["Dating","Relationships","Couples","Friendship","Family","Personality","Pet Peeves"] },
  { name: "Fun & Chaos", cats: ["Would You Rather","Hypotheticals","Chaos","Internet","Memes","Embarrassing","Gross","Unhinged"] },
  { name: "Life", cats: ["Lifestyle","Money","School","Work","Fashion","Beauty","Shopping","Home"] },
  { name: "Going Out", cats: ["Travel","Vacation","Cities","Experiences","Bucket List"] },
  { name: "Entertainment", cats: ["Music","Movies","TV","Video Games","Sports","Hobbies"] },
  { name: "Feels", cats: ["Nostalgia","Childhood","Deep","Wholesome"] },
  { name: "Wildcards", cats: ["Random","Animals"] }
];

/* prompt: {c: category, q: question, items: [5 rankable items]} */
GC.PROMPTS = [
{c:"Random",q:"Things you'd grab in a fire (people and pets are safe)",items:["Phone","Laptop","Photo albums","Favorite hoodie","Wallet"]},
{c:"Random",q:"Best excuses for being late",items:["Traffic was insane","Alarm didn't go off","Lost track of time","Thought it was tomorrow","Car trouble"]},
{c:"Random",q:"Weirdest things to find in a couch",items:["Loose change","The remote","Ancient snacks","One sock","Someone's retainer"]},
{c:"Food",q:"Best comfort foods",items:["Mac and cheese","Pizza","Ramen","Fried chicken","Mashed potatoes"]},
{c:"Food",q:"Best breakfast foods",items:["Pancakes","Bacon and eggs","Breakfast burrito","Cereal","French toast"]},
{c:"Food",q:"Cuisines you'd eat forever",items:["Mexican","Japanese","Italian","Indian","Thai"]},
{c:"Drinks",q:"Best coffee orders",items:["Iced latte","Cold brew","Cappuccino","Espresso","Frappuccino"]},
{c:"Drinks",q:"Best sodas",items:["Coca-Cola","Dr Pepper","Sprite","Root beer","Mountain Dew"]},
{c:"Drinks",q:"Best BBQ drinks",items:["Lemonade","Iced tea","Beer","Soda","Sparkling water"]},
{c:"Fast Food",q:"Best fast food chains",items:["Chick-fil-A","McDonald's","In-N-Out","Taco Bell","Wendy's"]},
{c:"Fast Food",q:"Best fast food fries",items:["McDonald's","Chick-fil-A waffle fries","Five Guys","Wendy's","Arby's curly fries"]},
{c:"Fast Food",q:"Best fast food burgers",items:["Five Guys","In-N-Out","Shake Shack","Wendy's","Burger King"]},
{c:"Snacks",q:"Best movie snacks",items:["Popcorn","Candy","Nachos","Pretzels","Ice cream"]},
{c:"Snacks",q:"Best chips",items:["Doritos","Lay's","Kettle chips","Tortilla chips","Cheetos"]},
{c:"Snacks",q:"Best gas station snacks",items:["Beef jerky","Candy bar","Chips","Donuts","Trail mix"]},
{c:"Desserts",q:"Best desserts",items:["Ice cream","Chocolate cake","Cheesecake","Brownies","Cookies"]},
{c:"Desserts",q:"Best ice cream flavors",items:["Vanilla","Chocolate","Mint chip","Cookies and cream","Strawberry"]},
{c:"Desserts",q:"Best candy",items:["Reese's","Skittles","M&M's","Sour Patch Kids","Kit Kat"]},
{c:"Travel",q:"Best ways to travel",items:["Road trip","First-class flight","Mountain train","Cruise","Camper van"]},
{c:"Travel",q:"Best travel companions",items:["Best friend","Partner","Sibling","Solo","Parent"]},
{c:"Travel",q:"Biggest tourist traps",items:["Times Square","Hollywood Walk of Fame","The Bean in Chicago","Leaning Tower photo ops","The Vegas Strip"]},
{c:"Vacation",q:"Best vacation vibes",items:["Beach resort","Mountain cabin","City exploring","Countryside cottage","All-inclusive"]},
{c:"Vacation",q:"Best things to do on vacation",items:["Sleep in","Try local food","Explore","Swim","Absolutely nothing"]},
{c:"Vacation",q:"Worst vacation disasters",items:["Lost luggage","Food poisoning","Missed flight","Terrible hotel","Rain all week"]},
{c:"Cities",q:"Best US cities to visit",items:["New York","San Francisco","Chicago","New Orleans","Seattle"]},
{c:"Cities",q:"Best cities for food",items:["New Orleans","New York","San Francisco","Chicago","Austin"]},
{c:"Cities",q:"Cities with the best vibes",items:["New Orleans","Austin","San Diego","Nashville","Portland"]},
{c:"Lifestyle",q:"Best daily rituals",items:["Morning coffee","Evening walk","Reading before bed","Workout","Journaling"]},
{c:"Lifestyle",q:"Signs you've made it",items:["Debt-free","Work optional","Dream home","Travel anytime","Helping family"]},
{c:"Lifestyle",q:"Best simple pleasures",items:["Fresh sheets","First sip of coffee","Rainy day inside","Good stretch","Sunset"]},
{c:"Money",q:"Best things to spend money on",items:["Travel","Good food","Experiences with friends","Home comfort","Hobbies"]},
{c:"Money",q:"Dumbest things people overspend on",items:["Bottled water","Extended warranties","Designer basics","Lottery tickets","Cable TV"]},
{c:"Money",q:"You win $1M — first moves",items:["Pay off debt","Invest it","Help family","Travel","Buy a house"]},
{c:"Dating",q:"Best first date ideas",items:["Coffee","Mini golf","Nice dinner","Hike","Museum"]},
{c:"Dating",q:"Biggest dating green flags",items:["Good listener","Funny","Kind to waiters","Has goals","Remembers details"]},
{c:"Dating",q:"Biggest dating red flags",items:["Rude to staff","Talks about ex constantly","No ambition","Love-bombs","Brags about being nice"]},
];

GC.PROMPTS = GC.PROMPTS.concat([
{c:"Relationships",q:"Most important things in a relationship",items:["Trust","Communication","Humor","Respect","Shared values"]},
{c:"Relationships",q:"Best relationship milestones",items:["First trip together","Meeting the family","Moving in","Saying I love you","Surviving IKEA together"]},
{c:"Relationships",q:"Dumbest fight starters",items:["Dishes in the sink","Phone at dinner","Thermostat wars","Backseat driving","The 'what's for dinner' loop"]},
{c:"Couples",q:"Best couple activities",items:["Cook together","Game night","Travel","Hiking","Movie marathon"]},
{c:"Couples",q:"Cutest couple habits",items:["Inside jokes","Good morning texts","Kitchen slow dances","Finishing sentences","Stealing fries"]},
{c:"Couples",q:"Most annoying couple habits",items:["Baby talk in public","Constant PDA","Matching outfits","Posting everything","Blanket hogging"]},
{c:"Friendship",q:"Best friend qualities",items:["Loyal","Funny","Honest","Shows up","Good texter"]},
{c:"Friendship",q:"Best friend activities",items:["Road trips","Late-night talks","Game nights","Trying restaurants","Doing nothing together"]},
{c:"Friendship",q:"Friendship red flags",items:["Only calls when they need something","Cancels constantly","Gossips about you","Always competes","Never asks about you"]},
{c:"Family",q:"Best family traditions",items:["Holiday dinners","Annual vacation","Game night","Birthday rituals","Sunday calls"]},
{c:"Family",q:"Classic family roles",items:["The planner","The funny one","The peacemaker","The dramatic one","The quiet one"]},
{c:"Family",q:"Most chaotic family events",items:["Thanksgiving dinner","Family road trip","Reunions","Moving day","Weddings"]},
{c:"Personality",q:"Best personality traits",items:["Funny","Kind","Honest","Adventurous","Calm"]},
{c:"Personality",q:"Most attractive non-physical traits",items:["Confidence","Humor","Ambition","Kindness","Intelligence"]},
{c:"Personality",q:"Party personality types",items:["The dancer","The deep-talker","The snack guardian","The early leaver","The 'one more drink' one"]},
{c:"Pet Peeves",q:"Most annoying everyday things",items:["Slow walkers","Loud chewing","Speakerphone in public","Being interrupted","Reply-all emails"]},
{c:"Pet Peeves",q:"Driving pet peeves",items:["No turn signal","Tailgating","Left-lane campers","No thank-you wave","Honking instantly"]},
{c:"Pet Peeves",q:"Roommate pet peeves",items:["Dishes in the sink","Eating your food","Loud at night","Thermostat wars","Never buying toilet paper"]},
{c:"Would You Rather",q:"You HAVE to pick one — rank best to worst",items:["Fight one horse-sized duck","Fight 100 duck-sized horses","Eat a whole raw onion","Give up your phone for a month","Lick a subway pole"]},
{c:"Would You Rather",q:"Superpowers you'd actually want",items:["Teleportation","Freeze time","Invisibility","Super strength","Mind reading"]},
{c:"Would You Rather",q:"Weird talents, ranked",items:["Perfect impressions","Juggling","Speed reading","Touch nose with tongue","Wiggling ears"]},
{c:"Hypotheticals",q:"Invisible for a day — what first?",items:["Sneak backstage at a concert","Hear what people really say","Harmless pranks","Explore a closed museum","Skip every line"]},
{c:"Hypotheticals",q:"If you could time travel",items:["Meet your younger self","See the future","Witness history","Fix one mistake","Party in the 80s"]},
{c:"Hypotheticals",q:"If money were no object",items:["Buy an island","Fund friends' dreams","Travel forever","Build a dream home","Start a charity"]},
{c:"Chaos",q:"Most chaotic wedding moves",items:["Dive for the bouquet","Unhinged speech","Start a dance-off","Object during the vows","Rearrange the seating chart"]},
{c:"Chaos",q:"Chaos energy, ranked",items:["Raccoon","Toddler after sugar","Drunk uncle","Group chat at 2am","Monday morning"]},
{c:"Chaos",q:"Best harmless chaos",items:["Reply-all 'noted'","Rearrange the fridge","Hide one shoe","Start a slow clap","Change a friend's autocorrect"]},
{c:"Internet",q:"Best corners of the internet",items:["Cat videos","Cooking TikTok","Wikipedia rabbit holes","Wholesome memes","Ancient forum threads"]},
{c:"Internet",q:"Most annoying internet things",items:["Autoplay videos","Pop-up ads","Accept-all-cookies walls","Buffering","Spoilers"]},
{c:"Internet",q:"Websites you'd miss most",items:["YouTube","Google","Reddit","Spotify","Wikipedia"]},
{c:"Memes",q:"Meme formats that never die",items:["Distracted boyfriend","Drake Hotline Bling","Woman yelling at cat","This is fine","Surprised Pikachu"]},
{c:"Memes",q:"Best meme categories",items:["Reaction memes","Wholesome memes","Dank memes","Relatable memes","Animal memes"]},
{c:"Memes",q:"Dead memes, ranked by the fall",items:["Harlem Shake","Gangnam Style","Ice bucket challenge","Planking","Mannequin challenge"]},
{c:"Nostalgia",q:"Best 2000s nostalgia",items:["Blockbuster nights","AIM away messages","Burned CDs","Flip phones","Saturday morning cartoons"]},
{c:"Nostalgia",q:"Nostalgic snacks",items:["Dunkaroos","Gushers","Bagel Bites","Push Pops","Fruit by the Foot"]},
{c:"Nostalgia",q:"Things kids today will never know",items:["The dial-up tone","Rewinding a VHS","Blowing on cartridges","Phone books","Waiting for film to develop"]},
]);

GC.PROMPTS = GC.PROMPTS.concat([
{c:"Childhood",q:"Best playground equipment",items:["Swings","Slide","Monkey bars","Merry-go-round","Climbing wall"]},
{c:"Childhood",q:"Best childhood games",items:["Hide and seek","Tag","Kickball","Four square","Capture the flag"]},
{c:"Childhood",q:"Best school lunch items",items:["Pizza day","Chicken nuggets","Chocolate milk","Tater tots","Ice cream sandwich"]},
{c:"Music",q:"Best music eras",items:["80s","90s","2000s","70s","2010s"]},
{c:"Music",q:"Best concert experiences",items:["Front row","Festival with friends","Tiny venue","Stadium show","Drive-in concert"]},
{c:"Music",q:"Most overplayed party songs",items:["Cha Cha Slide","Cupid Shuffle","YMCA","Wobble","Electric Slide"]},
{c:"Movies",q:"Best movie genres",items:["Comedy","Action","Sci-fi","Horror","Romance"]},
{c:"Movies",q:"Best movie theater snacks",items:["Popcorn","Nachos","Candy","Hot dog","Soft pretzel"]},
{c:"Movies",q:"Most quotable movies",items:["Mean Girls","Step Brothers","The Hangover","Superbad","Anchorman"]},
{c:"TV",q:"Best TV genres",items:["Comedy","Drama","Reality","Documentary","Sci-fi"]},
{c:"TV",q:"Most binge-worthy shows",items:["The Office","Breaking Bad","Stranger Things","Friends","Ted Lasso"]},
{c:"TV",q:"Reality TV, ranked",items:["Survivor","Great British Bake Off","Shark Tank","Love Is Blind","The Bachelor"]},
{c:"Video Games",q:"Best game genres",items:["RPG","Party games","Shooters","Puzzle","Sports"]},
{c:"Video Games",q:"Best party video games",items:["Mario Kart","Super Smash Bros","Jackbox","Mario Party","Among Us"]},
{c:"Video Games",q:"Most iconic game characters",items:["Mario","Pikachu","Link","Sonic","Master Chief"]},
{c:"Sports",q:"Best sports to watch",items:["Basketball","Football","Soccer","Baseball","Tennis"]},
{c:"Sports",q:"Best casual sports to play",items:["Basketball","Tennis","Volleyball","Bowling","Golf"]},
{c:"Sports",q:"Most intense rivalries",items:["Yankees vs Red Sox","Lakers vs Celtics","Alabama vs Auburn","El Clasico","Ohio State vs Michigan"]},
{c:"Hobbies",q:"Best low-cost hobbies",items:["Hiking","Reading","Cooking","Drawing","Running"]},
{c:"Hobbies",q:"Hobbies that make you interesting",items:["Playing an instrument","Speaking another language","Photography","Cooking","Travel"]},
{c:"Hobbies",q:"Hobbies people quit by February",items:["Going to the gym","Journaling","Meditation","Learning guitar","Meal prep"]},
{c:"School",q:"Best school subjects",items:["Lunch","Recess","Art","Music","PE"]},
{c:"School",q:"Worst parts of school",items:["Pop quizzes","Homework","Group projects","Early mornings","Standardized tests"]},
{c:"School",q:"Best school memories",items:["Field trips","Pep rallies","Snow days","Last day of school","Talent shows"]},
{c:"Work",q:"Best parts of working from home",items:["No commute","Sweatpants","Own snacks","Naps","No small talk"]},
{c:"Work",q:"Worst meeting types",items:["Could've been an email","Monday 8am","No agenda","Mandatory cameras on","The hour-long 'quick sync'"]},
{c:"Work",q:"Best excuses to leave early",items:["Dentist appointment","Vague 'family thing'","Car trouble","Migraine","Just quietly leaving"]},
{c:"Fashion",q:"Best wardrobe staples",items:["White sneakers","Good jeans","Black tee","Hoodie","Versatile jacket"]},
{c:"Fashion",q:"Trends that should stay dead",items:["Low-rise jeans","Frosted tips","Ed Hardy","Tiny sunglasses","Wallet chains"]},
{c:"Fashion",q:"Best-dressed occasions",items:["Wedding guest","Date night","Job interview","Holiday party","First day of school"]},
{c:"Beauty",q:"Best self-care",items:["Skincare routine","Fresh haircut","Face mask","Hot bath","Getting nails done"]},
{c:"Beauty",q:"Products actually worth it",items:["Sunscreen","Moisturizer","Lip balm","Good shampoo","Concealer"]},
{c:"Beauty",q:"Most overhyped beauty trends",items:["10-step routines","Jade rolling","Charcoal everything","Snail mucin","Expensive water"]},
{c:"Shopping",q:"Best places to shop",items:["Costco","Target","Thrift stores","Amazon","Local markets"]},
{c:"Shopping",q:"Most dangerous stores for your wallet",items:["Target","Costco","IKEA","Apple Store","HomeGoods"]},
{c:"Shopping",q:"Best things to buy in bulk",items:["Toilet paper","Snacks","Coffee","Cleaning supplies","Batteries"]},
]);

GC.PROMPTS = GC.PROMPTS.concat([
{c:"Home",q:"Best rooms in a house",items:["Kitchen","Living room","Bedroom","Backyard","Home office"]},
{c:"Home",q:"Most satisfying home upgrades",items:["Good mattress","Blackout curtains","Great shower head","Dishwasher","Comfy couch"]},
{c:"Home",q:"Worst chores",items:["Dishes","Bathroom","Folding laundry","Vacuuming","Taking out trash"]},
{c:"Animals",q:"Best pets",items:["Dog","Cat","Fish","Bird","Hamster"]},
{c:"Animals",q:"Cutest baby animals",items:["Puppy","Kitten","Baby panda","Duckling","Baby elephant"]},
{c:"Animals",q:"Animals you'd least want to fight",items:["Hippo","Honey badger","Cassowary","Moose","Swan"]},
{c:"Experiences",q:"Best once-in-a-lifetime experiences",items:["Northern lights","Safari","Hot air balloon","Scuba diving","Favorite artist live"]},
{c:"Experiences",q:"Everyone should try once",items:["Solo trip","Camping","Live concert","Road trip","Fancy dinner alone"]},
{c:"Experiences",q:"Most overrated experiences",items:["Times Square on NYE","Overpriced brunch","Black Friday","Hour-long lines","Paying for VIP"]},
{c:"Bucket List",q:"Top bucket list trips",items:["Japan","Italy","Iceland","Greece","New Zealand"]},
{c:"Bucket List",q:"Bucket list adventures",items:["Skydive","Swim with dolphins","See the pyramids","Northern lights","Balloon over Cappadocia"]},
{c:"Bucket List",q:"Do before 30",items:["Travel internationally","Learn to cook well","See a live show","Take a road trip","Do something scary"]},
{c:"Embarrassing",q:"Most embarrassing moments",items:["Waving at someone not waving at you","Calling the teacher 'mom'","Tripping in public","Autocorrect fail","Walking into a glass door"]},
{c:"Embarrassing",q:"Things everyone secretly does",items:["Talking to themselves","Shower arguments","Phone-as-shield","Car lip-syncing","Rehearsing their order"]},
{c:"Embarrassing",q:"Worst text fails",items:["Wrong group chat","Autocorrect disaster","Triple-text spiral","Dry 'K.' energy","Accidental voice memo"]},
{c:"Gross",q:"Grossest things",items:["Public restroom","Wet socks","Hair in food","Porta-potty","Old sponge"]},
{c:"Gross",q:"Gross but satisfying",items:["Popping pimples","Cleaning ears","Peeling sunburn","Removing a splinter","Lint rolling"]},
{c:"Gross",q:"Most divisive foods",items:["Olives","Blue cheese","Oysters","Liver","Cilantro"]},
{c:"Deep",q:"Deep questions",items:["What's your biggest fear?","Advice for your younger self?","What matters most?","Do you believe in fate?","What are you grateful for?"]},
{c:"Deep",q:"What people are really searching for",items:["Purpose","Love","Belonging","Peace","Meaning"]},
{c:"Deep",q:"Life's biggest questions",items:["Why are we here?","What happens after?","What is happiness?","Are we alone?","What would you change?"]},
{c:"Wholesome",q:"Most wholesome things",items:["Puppy videos","Grandparents' love","Thank-you notes","Kids laughing","Helping a stranger"]},
{c:"Wholesome",q:"Wholesome activities",items:["Volunteering","Baking for neighbors","Calling grandma","Complimenting strangers","Donating"]},
{c:"Wholesome",q:"Wholesome compliments",items:["You're a great friend","You make people happy","I'm proud of you","You matter","Thanks for being you"]},
{c:"Unhinged",q:"Unhinged intrusive thoughts",items:["What if I just kept driving?","Scream in the quiet room","Jump the fence","Send the text","Quit and farm goats"]},
{c:"Unhinged",q:"Unhinged but legal",items:["Yell-sing in the car","Cereal for dinner","7pm nap","Dye your hair","Adopt a weird pet"]},
{c:"Unhinged",q:"Unhinged group chat behavior",items:["37 texts at 3am","Voice memo essays","'lol' to everything","Memes mid-argument","Typing... for 10 minutes"]},
]);

/* Spicy bank — only used when the Spicy setting is on */
GC.SPICY = [
{c:"Spicy",q:"Best date night ideas",items:["Rooftop dinner","Stargazing","Cooking together","Dancing","Late-night drive"]},
{c:"Spicy",q:"Most attractive qualities",items:["Confidence","Sense of humor","Ambition","Kindness","Mystery"]},
{c:"Spicy",q:"Spiciest compliments",items:["You look incredible","Can't stop thinking about you","You smell amazing","That outfit though","Come here often?"]},
{c:"Spicy",q:"Best first-kiss settings",items:["Under the stars","In the rain","At a concert","On a rooftop","By the ocean"]},
{c:"Spicy",q:"Flirtiest texts",items:["Thinking about you","You looked good today","Can't wait to see you","Sweet dreams","Guess what I'm wearing"]},
{c:"Spicy",q:"Hottest movie moments",items:["The Notebook rain scene","Dirty Dancing lift","Ghost pottery scene","Titanic car scene","A Walk to Remember"]},
{c:"Spicy",q:"Best romantic gestures",items:["Surprise date","Handwritten letter","Slow dance","Breakfast in bed","Stargazing picnic"]},
{c:"Spicy",q:"Turn-ons (keep it classy)",items:["Great conversation","Confidence","Laughing together","Eye contact","Ambition"]},
{c:"Spicy",q:"Biggest turn-offs",items:["Arrogance","Bad hygiene","Rudeness","No humor","Clinginess"]},
{c:"Spicy",q:"Ideal date progression",items:["Drinks","Dinner","Evening walk","Stargazing","Goodnight kiss"]},
{c:"Spicy",q:"Spiciest would-you-rathers",items:["Kiss on the first date","Beach romance","Slow dance","Love letter","Candlelit dinner"]},
{c:"Spicy",q:"Most romantic songs",items:["Perfect — Ed Sheeran","All of Me — John Legend","Thinking Out Loud","At Last — Etta James","Can't Help Falling in Love"]},
{c:"Spicy",q:"Romantic movie nights",items:["The Notebook","Pride & Prejudice","Crazy Rich Asians","La La Land","10 Things I Hate About You"]},
{c:"Spicy",q:"Flirty pet names, ranked",items:["Babe","Honey","Love","Cutie","Snugglebug"]},
{c:"Spicy",q:"Best anniversary ideas",items:["Weekend getaway","Recreate the first date","Fancy dinner","Memory book","Surprise party"]},
];
